/* Copyright (C) 2004 TrueCrypt Team, truecrypt.org
   This product uses components written by Paul Le Roux <pleroux@swprofessionals.com> */

/* Everything below this line is automatically updated by the -mkproto-tool- */

int FormatVolume ( char *lpszFilename , BOOL bDevice , unsigned __int64 size , char *lpszPassword , int cipher , int pkcs5 , fatparams *ft, BOOL quickFormat, HWND hwndDlg );
