/* Copyright (C) 2004 TrueCrypt Foundation
   This product uses components written by Paul Le Roux <pleroux@swprofessionals.com> */


/* Everything below this line is automatically updated by the -mkproto-tool- */

void VerifyPasswordAndUpdate ( HWND hwndDlg , HWND hButton , HWND hPassword , HWND hVerify , char *szPassword , char *szVerify );
int ChangePwd ( char *lpszVolume , char *lpszOldPassword , char *lpszPassword );
