//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Common.rc
//
#define IDB_ABOUT                       50
#define IDI_TRUECRYPT_ICON              501
#define IDI_TRUECRYPT_ICON_B            502
#define IDD_BENCHMARK_DLG               503
#define IDD_MOUNT_OPTIONS               504
#define IDD_KEYFILES                    505
#define IDR_LANGUAGE                    506
#define IDI_TRUECRYPT                   507
#define IDD_ABOUT_DLG                   508
#define IDD_COMMANDHELP_DLG             509
#define IDD_RAWDEVICES_DLG              510
#define IDC_HOMEPAGE                    511
#define IDR_COMMON_RSRC_HEADER          512
#define IDD_LANGUAGE                    513
#define IDD_LEGAL_NOTICES               514
#define IDD_CIPHER_TEST_DLG             515
#define IDR_LICENSE                     516
#define IDC_KEY                         5000
#define IDC_PLAINTEXT                   5001
#define IDC_CIPHERTEXT                  5002
#define IDC_LEGAL_NOTICES               5003
#define IDC_LRW_KEY                     5004
#define IDD_LEGAL_NOTICES_DLG           5005
#define IDC_LRW_BLOCK_INDEX             5006
#define IDD_KEYFILE_GENERATOR           5007
#define IDC_CIPHER                      5008
#define IDD_MULTI_CHOICE_DLG            5009
#define IDC_POOL_CONTENTS               5010
#define IDC_PRF_ID                      5011
#define IDC_KEY_SIZE                    5012
#define IDC_PLAINTEXT_SIZE              5013
#define IDC_REDTICK                     5014
#define IDC_TESTS_MESSAGE               5015
#define IDC_RESET                       5016
#define IDC_AUTO                        5017
#define IDC_DECRYPT                     5018
#define IDT_TEST_KEY                    5019
#define IDT_TEST_PLAINTEXT              5020
#define IDT_PRF                         5021
#define IDT_LRW_MODE                    5022
#define IDT_TEST_CIPHERTEXT             5023
#define IDT_KEY                         5024
#define IDT_PLAINTEXT                   5025
#define IDC_ENCRYPT                     5026
#define IDT_KEY_UNIT                    5027
#define IDT_CIPHER                      5028
#define IDT_PLAINTEXT_SIZE_UNIT         5029
#define IDC_DEVICELIST                  5030
#define IDT_LRW_KEY                     5031
#define IDC_PERFORM_BENCHMARK           5032
#define IDT_LRW_BLOCK_INDEX             5033
#define IDC_KEYFILES_HIDVOL_PROT        5034
#define IDC_KEYLIST                     5035
#define IDC_ABOUT_IMG                   5036
#define IDT_ABOUT_VERSION               5037
#define IDT_BOX_BENCHMARK_INFO          5038
#define IDC_ABOUT_CREDITS               5039
#define IDT_SORT_METHOD                 5040
#define IDC_MOUNT_READONLY              5041
#define IDC_MOUNT_REMOVABLE             5042
#define IDC_PROTECT_HIDDEN_VOL          5043
#define IDC_COMMANDHELP_TEXT            5044
#define IDT_HIDDEN_PROT_PASSWD          5045
#define IDC_RESULTS                     5046
#define IDC_KEYADD                      5047
#define IDC_KEYREMOVE                   5048
#define IDC_KEYREMOVEALL                5049
#define IDC_KEYFILES_ENABLE             5050
#define IDT_HIDDEN_VOL_PROTECTION       5051
#define IDC_ADD_KEYFILE_PATH            5052
#define IDC_BENCHMARK_BUFFER_SIZE       5053
#define IDC_SHOW_PASSWORD_MO            5054
#define IDC_GENERATE_KEYFILE            5055
#define IDC_BENCHMARK_SORT_METHOD       5056
#define IDC_PASSWORD_PROT_HIDVOL        5057
#define IDT_BUFFER_SIZE                 5058
#define IDC_LANGLIST                    5059
#define IDC_KEYFILES_ENABLE_HIDVOL_PROT 5060
#define IDT_KEYFILES_NOTE               5061
#define IDT_KEYFILE_WARNING             5062
#define IDT_KEYFILE_GENERATOR_NOTE      5063
#define IDC_GENERATE_AND_SAVE_KEYFILE   5064
#define IDT_POOL_CONTENTS               5065
#define IDC_GET_LANG_PACKS              5066
#define IDT_LANGPACK_AUTHORS            5067
#define IDC_LANGPACK_CREDITS            5068
#define IDC_LANGPACK_VERSION            5069
#define IDT_ACTIVE_LANG_PACK            5070
#define IDC_DISPLAY_POOL_CONTENTS       5071
#define IDC_LRW_MODE                    5072
#define IDC_LRW_MODE_ENABLED            5073
#define IDC_LRW_INDEX_LSB               5074
#define IDC_MULTI_CHOICE_MSG            5075
#define IDC_CHOICE1                     5076
#define IDC_CHOICE5                     5077
#define IDC_CHOICE2                     5078
#define IDC_CHOICE3                     5079
#define IDC_CHOICE4                     5080
#define IDC_CHOICE6                     5081
#define IDC_CHOICE7                     5082
#define IDC_CHOICE8                     5083
#define IDC_CHOICE9                     5084
#define IDC_CHOICE10                    5085
#define IDC_MC_DLG_HR1                  5086
#define IDC_MC_DLG_HR2                  5087
#define IDC_DONATIONS                   5088
#define IDC_LINK_HIDVOL_PROTECTION_INFO 5089
#define IDC_LINK_KEYFILES_INFO          5090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        517
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         5091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
