#
# THIS MAKEFILE WORKS WITH MICROSOFT NMAKE ONLY
#

# change this to point to your DDK
DDK = C:\SDK\WINDDK\3790
OS = wxp

BASENAME = truecrypt

CC = cl
ASM = ml

all: $(BASENAME).sys

OBJECTS = Ntdriver.obj Ntvol.obj Ntrawdv.obj Ntfiledv.obj \
	Volumes.obj Crypto.obj Endian.obj Crc.obj Pkcs5.obj Cache.obj \
	Driver.res


!IFNDEF RELEASE

# Debug

DEFINES_D = -D_X86_=1 -Di386=1 -DSTD_CALL -DCONDITION_HANDLING=1 \
-DNT_UP=1 -DNT_INST=0 -DWIN32=100 -D_NT1X_=100 \
-DWINNT=1 -D_WIN32_WINNT=0x0400 -DWIN32_LEAN_AND_MEAN=1 -DDBG=1 -D_DEBUG -DDEBUG -DDEVL=1 \
-DFPO=0 -D_DLL=1 -D_IDWBUILD -DRDRDBG -DSRVDBG -DDBG_MESSAGES=1 \
-D_UNICODE -DLITTLE_ENDIAN

CFLAGS_D = $(DEFINES_D) -Zel -Zp8 -Gy -cbstring -Gz -QIfdiv- -QIf -Gi- -Gm- -GX- \
-GR- -GF -FI$(DDK)\inc\$(OS)\warning.h -Z7 -Od -Oi -Oy- -W3

LFLAGS_D = -MERGE:_PAGE=PAGE -MERGE:_TEXT=.text -SECTION:INIT,d \
-INCREMENTAL:NO -FORCE:MULTIPLE -RELEASE -FULLBUILD \
-IGNORE:4001,4037,4039,4065,4070,4078,4087,4089,4096 -NODEFAULTLIB \
-debug -version:4.00 -osversion:4.00 \
-MERGE:.rdata=.text -MAP:$(BASENAME).map -driver -align:0x20 \
-subsystem:native,4.00 -base:0x10000 -entry:DriverEntry@8

CRYPTOLIB = ..\..\crypto\debug\crypto.lib
COPYRELEASE =

!ELSE

# Release

DEFINES_D = -D_X86_=1 -Di386=1 -DSTD_CALL -DCONDITION_HANDLING=1 \
-DNT_UP=1 -DNO_DISK_ACCESS -DNT_INST=0 -DWIN32=100 -D_NT1X_=100 \
-DWINNT=1 -D_WIN32_WINNT=0x0400 -DWIN32_LEAN_AND_MEAN=1 -DDEVL=1 \
-DFPO=1 -DNDEBUG -D_DLL=1 -D_IDWBUILD -D_UNICODE \
-DLITTLE_ENDIAN

CFLAGS_D = $(DEFINES_D) -Zel -Zp8 -Gy -cbstring -Gz -QIfdiv- -QIf -Gi- -Gm- -GX- \
-GR- -GF -Oxs -Oy -FI$(DDK)\inc\$(OS)\warning.h -W3 -FAcs 

LFLAGS_D = -MERGE:_PAGE=PAGE -MERGE:_TEXT=.text -SECTION:INIT,d \
-INCREMENTAL:NO -FORCE:MULTIPLE -RELEASE -FULLBUILD \
-IGNORE:4001,4037,4039,4065,4070,4078,4087,4089,4096 -NODEFAULTLIB -version:4.00 \
-osversion:4.00 -MERGE:.rdata=.text -MAP:$(BASENAME).map -driver \
-align:0x20 -subsystem:native,4.00 -base:0x10000 -entry:DriverEntry@8

CRYPTOLIB = ..\..\crypto\release\crypto.lib
COPYRELEASE = copy $(BASENAME).sys "..\..\release\setup files"

!ENDIF

LINK_D = link $(LFLAGS_D) -nologo -out:$(BASENAME).sys -machine:IX86 \
	$(DDK)\lib\$(OS)\i386\ntoskrnl.lib \
	$(DDK)\lib\$(OS)\i386\hal.lib 

CFLAGS = $(CFLAGS_D) -nologo -DNT4_DRIVER -I$(DDK)\inc\$(OS) -I$(DDK)\inc\ddk\$(OS) -I$(DDK)\inc\ddk\wdm\$(OS) -YXTCdefs.h


{..}.c{}.obj :
	@$(CC) -c $(CFLAGS) -I..\..\common -I..\..\crypto $<

{..\..\common}.c{}.obj :
	@$(CC) -c $(CFLAGS) -I..\..\common -I..\..\crypto $<
	
{..}.rc{}.res :
	rc -r -D_X86_ -fo driver.res $< 


$(BASENAME).sys : $(OBJECTS) $(CRYPTOLIB)
	$(LINK_D) $(OBJECTS) $(CRYPTOLIB)
	$(COPYRELEASE)

