#
# THIS MAKEFILE WORKS WITH MICROSOFT NMAKE ONLY
#

# Windows DDK path
DDK = c:\SDK\WinDDK\Win98
OS = win98

BASENAME = truecrypt

CC = cl
ASM = ml

all: $(BASENAME).vxd

OBJECTS = Tc9x.obj Volumes.obj Crypto.obj Endian.obj Crc.obj \
		Pkcs5.obj Ifshook.obj Queue.obj Cache.obj Devdcl.obj

!IFNDEF RELEASE

# Debug
CFLAGS = -D_X86_ -DDEBLEVEL=1  -DBLD_COFF -DDEBUG -nologo -DIS_32 -DWIN32 -Gs -Zdpl -Od -YX -W3 \
      -DWIN9X_DRIVER -I.. -I$(DDK)\inc\$(OS) -I$(DDK)\src\BLOCK\inc -YXTCdefs.h -FAcs

LFLAGS = -machine:i386  -out:$@  -def:../truecrypt.def -debug -debugtype:map -map:$*.map \
      -vxd vxdwraps.clb -nodefaultlib -ignore:4039,4078 -nologo \
      -LIBPATH:$(DDK)\lib\$(OS) -LIBPATH:$(DDK)\lib\i386\free
      
CRYPTOLIB = ..\..\crypto\debug\crypto.lib
COPYRELEASE =

!ELSE

# Release
CFLAGS = -D_X86_ -DDEBLEVEL=1  -DBLD_COFF -DRELEASE -nologo -DIS_32 -DWIN32 -Zdpl -O2 -YX -W3 \
      -DWIN9X_DRIVER -I.. -I$(DDK)\inc\$(OS) -I$(DDK)\src\BLOCK\inc -YXtcdefs.h -FAcs

LFLAGS = -nologo -machine:i386  -out:$@  -def:../truecrypt.def -release \
      -vxd vxdwraps.clb -nodefaultlib -ignore:4039,4069,4078 -nologo \
      -LIBPATH:$(DDK)\lib\$(OS) -LIBPATH:$(DDK)\lib\i386\free

CRYPTOLIB = ..\..\crypto\release\crypto.lib
COPYRELEASE = copy $(BASENAME).vxd "..\..\release\setup files"

!ENDIF

ASMFLAGS = -I\$(DDK)\inc\$(OS) -coff -DBLD_COFF -DIS_32 -W2 -c -Cx -DMASM6 -nologo

{..}.c{}.obj :
	@$(CC) -c $(CFLAGS) -I..\..\common -I..\..\crypto 	$<

{..}.asm{}.obj :
	@$(ASM) /I.. /I$(DDK)\inc\$(OS) $(ASMFLAGS) $<

{../../common}.c{}.obj :
	@$(CC) -c $(CFLAGS) -I..\..\common -I..\..\crypto 	$<


$(BASENAME).vxd : $(OBJECTS) $(CRYPTOLIB)
	link $(LFLAGS) $(OBJECTS) $(CRYPTOLIB)
#   nmsym /TRANSLATE:SOURCE,PACKAGE,ALWAYS $@
	$(COPYRELEASE)
		

